In [380]:
import pandas as pd
from sklearn.feature_selection import SelectKBest, f_regression
from scipy.stats import spearmanr, pearsonr

# Load the tables 
covid_df = pd.read_csv('../data/covid.csv', index_col=False)
precovid_df = pd.read_csv('../data/precovid.csv', index_col=False)
postcovid_df = pd.read_csv('../data/postcovid.csv', index_col=False)

### Pearson Correlation Coefficient Feature Selection

Features that impacted layoffs during covid, before covid and post covid using filtering technique called Pearsonr and Selectkbest.

In [381]:
def pearsonr_feature_selection(inp_df):
    input_df = inp_df.drop(columns={'Number of Workers','percent_layoff','Unnamed: 0'})
    X = input_df
    y = inp_df['Number of Workers']
    correlations = []
    temp = []
    for col in X.columns:
        corr, _ = pearsonr(X[col].values, y)
        temp.append(corr)

    df = pd.DataFrame(temp, columns=['pearsonr'], index=X.columns)

    # Select the top K features with the highest correlation
    k = 15
    selector = SelectKBest(f_regression, k=k)
    X_selected = selector.fit_transform(X, y)

    # Get the indices of the selected features
    selected_indices = selector.get_support(indices=True)

    # Get the names of the selected features
    selected_features = X.columns[selected_indices]

    # Create a new dataframe with the selected features
    selected_features_df = pd.DataFrame(X_selected, columns=selected_features)
    return selected_features_df, df.loc[selected_features_df.columns].sort_values(by=['pearsonr'],ascending=False)

In [382]:
precovid_features, precovid_df_pearson_cor = pearsonr_feature_selection(precovid_df)
covid_features, covid_df_pearson_cor = pearsonr_feature_selection(covid_df)
postcovid_features, postcovid_df_pearson_cor = pearsonr_feature_selection(postcovid_df)

In [383]:
precovid_df_pearson_cor

                                          pearsonr
Number of Layoffs                         0.360434
industry_labelled                         0.134383
commonStockIssued                         0.128812
employee_count                            0.120386
revenue                                   0.099013
costOfRevenue                             0.094625
costAndExpenses                           0.090348
deferredRevenueNonCurrent                 0.078608
stockBasedCompensation                    0.074697
totalInvestments                          0.073031
deferredRevenue                          -0.082343
debtRepayment                            -0.086886
netCashUsedProvidedByFinancingActivities -0.125271
EPS                                      -0.227670
EPSDiluted                               -0.228042

In [384]:
precovid_features

,Number of Layoffs,revenue,costOfRevenue,costAndExpenses,EPS,EPSDiluted,deferredRevenue,deferredRevenueNonCurrent,totalInvestments,stockBasedCompensation,debtRepayment,commonStockIssued,netCashUsedProvidedByFinancingActivities,employee_count,industry_labelled
0,1.0,1.196000e+10,9.014000e+09,1.068600e+10,1.490000,1.490000,9.266000e+09,5.249000e+09,0.000000e+00,0.000000e+00,-9.320000e+08,0.0,1.179000e+09,118033.0,2.0
1,1.0,5.326500e+10,3.284400e+10,4.065300e+10,0.590000,0.585000,7.403000e+09,2.878000e+09,2.117720e+11,1.351000e+09,-6.000000e+09,1000000.0,-3.152300e+10,132000.0,4.0
2,1.0,5.801500e+10,3.619400e+10,4.460000e+10,0.617500,0.615000,5.532000e+09,0.000000e+00,1.874230e+11,1.514000e+09,0.000000e+00,0.0,-2.945700e+10,137000.0,4.0
3,1.0,6.675900e+07,0.000000e+00,0.000000e+00,0.627539,0.627539,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,-6.018800e+07,3641.0,5.0
4,1.0,4.058000e+08,2.783000e+08,3.894000e+08,0.100000,0.090000,0.000000e+00,0.000000e+00,0.000000e+00,3.200000e+06,-1.160000e+07,0.0,-7.000000e+06,6700.0,11.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
338,1.0,4.317000e+08,2.961000e+08,3.684000e+08,0.750000,0.730000,0.000000e+00,0.000000e+00,0.000000e+00,5.300000e+06,0.000000e+00,0.0,1.010000e+07,7700.0,568.0
339,2.0,1.306900e+09,7.686000e+08,1.109500e+09,0.320000,0.320000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.0,-5.200000e+07,11500.0,570.0
340,1.0,1.307700e+09,7.565000e+08,1.081200e+09,0.320000,0.320000,0.000000e+00,0.000000e+00,1.731400e+09,0.000000e+00,-3.249000e+08,0.0,-1.660000e+08,11500.0,570.0
341,1.0,7.520050e+08,5.625160e+08,6.561570e+08,1.070000,1.020000,2.630700e+07,3.329270e+08,0.000000e+00,0.000000e+00,-3.929200e+08,9565000.0,-4.628500e+07,9000.0,571.0
342,1.0,9.462000e+08,4.465000e+08,8.784000e+08,0.180000,0.170000,0.000000e+00,0.000000e+00,0.000000e+00,9.200000e+06,-6.980000e+07,0.0,-9.920000e+07,4800.0,576.0

In [385]:
covid_df_pearson_cor

                                          pearsonr
deferredRevenueNonCurrent                 0.269051
Number of Layoffs                         0.260593
deferredRevenue                           0.254986
netCashUsedProvidedByFinancingActivities  0.234492
otherFinancingActivites                   0.163825
shortTermDebt                             0.161512
totalCurrentLiabilities                   0.160753
interestExpense                           0.146660
totalNonCurrentLiabilities                0.144072
freeCashFlow                             -0.141067
netIncome                                -0.145430
incomeBeforeTax                          -0.149569
incomeTaxExpense                         -0.163803
EPS                                      -0.251189
EPSDiluted                               -0.255602

In [386]:
covid_features

,Number of Layoffs,interestExpense,incomeBeforeTax,incomeTaxExpense,netIncome,EPS,EPSDiluted,shortTermDebt,deferredRevenue,totalCurrentLiabilities,deferredRevenueNonCurrent,totalNonCurrentLiabilities,otherFinancingActivites,netCashUsedProvidedByFinancingActivities,freeCashFlow
0,2.0,340000000.0,-3.095000e+09,-6.960000e+08,-2.399000e+09,-4.710000,-4.71,4.446000e+09,6.954000e+09,1.658400e+10,7.043000e+09,5.171700e+10,2.052000e+09,1.511000e+09,-3.181000e+09
1,3.0,371000000.0,-1.573000e+09,-3.230000e+08,-1.250000e+09,-1.970000,-1.97,4.039000e+09,7.921000e+09,1.733300e+10,7.055000e+09,5.926100e+10,1.075100e+10,7.013000e+09,1.740000e+08
2,1.0,13422000.0,2.525400e+08,6.258000e+07,1.899600e+08,2.750000,2.74,0.000000e+00,0.000000e+00,4.437559e+09,0.000000e+00,3.766587e+09,-1.052000e+06,-5.191350e+08,3.801700e+08
3,1.0,596000000.0,3.688000e+09,5.080000e+08,3.179000e+09,1.798273,1.78,6.672000e+09,0.000000e+00,2.853300e+10,0.000000e+00,1.067480e+11,8.790000e+08,-3.643000e+09,7.718000e+09
4,2.0,15900000.0,6.630000e+07,1.670000e+07,4.960000e+07,2.580000,2.57,5.940000e+08,0.000000e+00,8.932000e+08,0.000000e+00,1.328100e+09,5.791000e+08,-1.932000e+08,4.178000e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
264,1.0,8737000.0,4.501600e+07,6.551000e+06,3.846500e+07,0.620000,0.61,2.002820e+08,3.022200e+07,5.356280e+08,3.561750e+08,1.461275e+09,2.390360e+08,-1.478450e+08,1.505260e+08
265,1.0,64000000.0,-5.940000e+08,-5.000000e+06,-5.890000e+08,-3.360000,-3.36,1.520000e+08,0.000000e+00,2.141000e+09,4.970000e+08,6.756000e+09,1.691000e+09,1.323000e+09,-3.930000e+08
266,1.0,313000000.0,-2.661300e+10,-6.010000e+09,-2.007000e+10,-4.700000,-4.70,2.045800e+10,1.816500e+10,5.636300e+10,0.000000e+00,1.122570e+11,-7.800000e+07,-5.283000e+09,3.760000e+08
267,1.0,12300000.0,-1.199000e+08,-2.400000e+07,-9.540000e+07,-0.440000,-0.44,3.000000e+05,0.000000e+00,7.630000e+08,0.000000e+00,3.195800e+09,1.381300e+09,6.581000e+08,1.619000e+08
268,1.0,191000.0,-3.485400e+07,-1.086400e+07,-2.399000e+07,-0.330000,-0.33,5.640600e+07,3.918000e+06,1.205300e+08,0.000000e+00,1.716350e+08,6.824000e+06,6.824000e+06,6.512000e+06

In [387]:
postcovid_df_pearson_cor

                             pearsonr
Number of Layoffs            0.182791
Quarter                      0.177744
industry_labelled            0.117089
totalOtherIncomeExpensesNet  0.084031
EPS                         -0.083898
EPSDiluted                  -0.085844
intangibleAssets            -0.086847
effectOfForexChangesOnCash  -0.088625
goodwillAndIntangibleAssets -0.089090
new_deaths_per_million      -0.161509
new_deaths                  -0.161509
new_deaths_smoothed         -0.161947
new_cases_per_million       -0.193469
new_cases                   -0.193469
new_cases_smoothed          -0.194272

In [388]:
postcovid_features

,Quarter,Number of Layoffs,totalOtherIncomeExpensesNet,EPS,EPSDiluted,intangibleAssets,goodwillAndIntangibleAssets,effectOfForexChangesOnCash,industry_labelled,new_cases,new_cases_smoothed,new_cases_per_million,new_deaths,new_deaths_smoothed,new_deaths_per_million
0,4.0,1.0,0.000000e+00,0.00,0.00,2.059000e+09,6.150000e+09,0.0,2.0,48271.978261,46706.085435,142.694152,373.391304,371.183228,1.103793
1,1.0,1.0,2.120000e+08,2.52,2.51,7.398600e+10,1.062840e+11,7000000.0,6.0,287196.233333,298754.488933,848.964922,1783.786517,1806.499213,5.272989
2,3.0,1.0,-2.030000e+08,2.22,2.21,6.872500e+10,1.004510e+11,-59000000.0,6.0,94138.326087,95996.048098,278.277120,430.739130,424.852424,1.273250
3,4.0,1.0,-7.800000e+06,1.11,1.10,2.290000e+08,1.903600e+09,1900000.0,9.0,114728.956522,106132.871109,339.143957,1335.913043,1344.720522,3.949033
4,3.0,1.0,-1.540000e+07,0.74,0.73,3.785000e+08,2.864100e+09,-1000000.0,9.0,94138.326087,95996.048098,278.277120,430.739130,424.852424,1.273250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99,2.0,2.0,-1.140000e+08,1.42,1.41,8.340000e+08,9.856000e+09,0.0,562.0,76131.879121,73506.604352,225.049198,363.747253,370.029835,1.075264
100,1.0,1.0,-2.417000e+09,0.74,0.74,0.000000e+00,2.943800e+10,49000000.0,563.0,287196.233333,298754.488933,848.964922,1783.786517,1806.499213,5.272989
101,2.0,2.0,-2.100000e+08,1.88,1.88,0.000000e+00,2.866400e+10,-149000000.0,563.0,76131.879121,73506.604352,225.049198,363.747253,370.029835,1.075264
102,1.0,1.0,-1.410000e+07,0.15,0.15,3.143600e+09,9.112900e+09,14300000.0,566.0,287196.233333,298754.488933,848.964922,1783.786517,1806.499213,5.272989
103,2.0,1.0,-2.870000e+07,1.48,1.47,3.031300e+09,8.960100e+09,-6600000.0,566.0,76131.879121,73506.604352,225.049198,363.747253,370.029835,1.075264

### Spearman Correlation Coefficient Feature Selection

Features that impacted layoffs during covid, before covid and post covid using filtering technique called Spearman and Selectkbest.

In [389]:
def spearman_feature_selection(inp_df, top_feature_count):
    input_df = inp_df.drop(columns={'Number of Workers','percent_layoff','Unnamed: 0'})
    X = input_df
    y = inp_df['Number of Workers']
    corr, _ = spearmanr(X, y)
    df = pd.DataFrame(corr[:-1,-1], columns=['spearman'], index=X.columns)
    spearman_df = df.sort_values(by=['spearman'], ascending=False).head(top_feature_count)
    X_selected = input_df[spearman_df.index]
    return X_selected, spearman_df

In [390]:
top_feature_count = 20
precovid_selected_features, precovid_df_spearman_cor = spearman_feature_selection(precovid_df, top_feature_count)
covid_selected_features, covid_df_spearman_cor = spearman_feature_selection(covid_df, top_feature_count)
postcovid_selected_features, postcovid_df_spearman_cor = spearman_feature_selection(postcovid_df, top_feature_count)

In [391]:
precovid_df_spearman_cor

                                                 spearman
Number of Layoffs                                0.351616
employee_count                                   0.188790
totalStockholdersEquity                          0.173315
commonStockIssued                                0.143684
revenue                                          0.143285
industry_labelled                                0.122443
depreciationAndAmortization_cash-flow-statement  0.116821
costOfRevenue                                    0.114081
weightedAverageShsOut                            0.113753
weightedAverageShsOutDil                         0.113514
depreciationAndAmortization                      0.113369
cashAtBeginningOfPeriod                          0.112755
otherInvestingActivites                          0.109023
costAndExpenses                                  0.099665
cashAndCashEquivalents                           0.098845
cashAtEndOfPeriod                                0.095867
propertyPlantEquipmentNet                        0.082921
accountPayables                                  0.076871
totalCurrentLiabilities                          0.074276
otherNonCurrentAssets                            0.071521

In [392]:
precovid_selected_features

,Number of Layoffs,employee_count,totalStockholdersEquity,commonStockIssued,revenue,industry_labelled,depreciationAndAmortization_cash-flow-statement,costOfRevenue,weightedAverageShsOut,weightedAverageShsOutDil,depreciationAndAmortization,cashAtBeginningOfPeriod,otherInvestingActivites,costAndExpenses,cashAndCashEquivalents,cashAtEndOfPeriod,propertyPlantEquipmentNet,accountPayables,totalCurrentLiabilities,otherNonCurrentAssets
0,1,118033.0,-2.200000e+07,0.0,1.196000e+10,2,0.000000e+00,9.014000e+09,4.450080e+08,4.455870e+08,0.000000e+00,3.480000e+08,-863000000.0,1.068600e+10,3.190000e+08,3.300000e+08,4.380400e+10,2.118000e+09,2.012300e+10,1.325000e+09
1,1,132000.0,1.149490e+11,1000000.0,5.326500e+10,4,2.665000e+09,3.284400e+10,1.952867e+10,1.970644e+10,2.665000e+09,4.505900e+10,-576000000.0,4.065300e+10,3.197100e+10,3.197100e+10,3.811700e+10,3.848900e+10,8.854800e+10,2.254600e+10
2,1,137000.0,1.058600e+11,0.0,5.801500e+10,4,3.040000e+09,3.619400e+10,1.869628e+10,1.880258e+10,3.040000e+09,4.477100e+10,86000000.0,4.460000e+10,3.798800e+10,3.981700e+10,3.874600e+10,3.044300e+10,9.377200e+10,3.458700e+10
3,1,3641.0,1.490057e+09,0.0,6.675900e+07,5,0.000000e+00,0.000000e+00,9.541878e+07,9.557832e+07,0.000000e+00,0.000000e+00,0.0,0.000000e+00,6.402060e+08,0.000000e+00,0.000000e+00,0.000000e+00,4.123130e+08,-1.169554e+09
4,1,6700.0,7.650000e+08,0.0,4.058000e+08,11,1.830000e+07,2.783000e+08,1.068000e+08,1.100000e+08,1.830000e+07,7.690000e+07,0.0,3.894000e+08,1.227000e+08,1.227000e+08,2.803000e+08,1.886000e+08,4.891000e+08,5.070000e+07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
338,1,7700.0,1.351800e+09,0.0,4.317000e+08,568,2.620000e+07,2.961000e+08,7.390000e+07,7.570000e+07,2.620000e+07,2.255000e+08,-26500000.0,3.684000e+08,2.973000e+08,2.973000e+08,8.220000e+08,1.252000e+08,2.888000e+08,2.170000e+07
339,2,11500.0,-1.970000e+07,0.0,1.306900e+09,570,6.110000e+07,7.686000e+08,4.233000e+08,4.268000e+08,6.110000e+07,1.217500e+09,-11000000.0,1.109500e+09,1.881300e+09,1.398200e+09,2.122000e+08,5.747000e+08,5.315300e+09,8.222000e+08
340,1,11500.0,-3.950000e+07,0.0,1.307700e+09,570,6.700000e+07,7.565000e+08,4.195000e+08,4.247000e+08,6.700000e+07,1.398200e+09,-25000000.0,1.081200e+09,1.818700e+09,1.456800e+09,3.866000e+08,6.019000e+08,5.163300e+09,3.314000e+08
341,1,9000.0,1.704311e+09,9565000.0,7.520050e+08,571,0.000000e+00,5.625160e+08,6.194100e+07,6.463300e+07,0.000000e+00,6.530300e+07,538000.0,6.561570e+08,6.330200e+07,6.330200e+07,1.063084e+09,2.430710e+08,6.426720e+08,1.897250e+08
342,1,4800.0,5.107700e+09,0.0,9.462000e+08,576,8.310000e+07,4.465000e+08,2.233000e+08,2.250000e+08,8.310000e+07,3.096000e+08,-33600000.0,8.784000e+08,2.254000e+08,2.254000e+08,1.017800e+09,2.690000e+08,8.706000e+08,6.720000e+07

In [393]:
covid_df_spearman_cor

                                       spearman
Number of Layoffs                      0.460103
propertyPlantEquipmentNet              0.272493
cashAndShortTermInvestments            0.259295
cashAtBeginningOfPeriod                0.257159
cashAndCashEquivalents                 0.247276
cashAtEndOfPeriod                      0.242813
totalCurrentLiabilities                0.242281
totalNonCurrentLiabilities             0.238829
totalCurrentAssets                     0.234866
totalLiabilities                       0.233017
costOfRevenue                          0.231092
longTermDebt                           0.230829
totalDebt                              0.227185
interestExpense                        0.226709
totalLiabilitiesAndStockholdersEquity  0.226282
totalAssets                            0.224896
accountPayables                        0.221097
totalNonCurrentAssets                  0.220637
costAndExpenses                        0.214593
shortTermDebt                          0.205417

In [394]:
covid_selected_features

,Number of Layoffs,propertyPlantEquipmentNet,cashAndShortTermInvestments,cashAtBeginningOfPeriod,cashAndCashEquivalents,cashAtEndOfPeriod,totalCurrentLiabilities,totalNonCurrentLiabilities,totalCurrentAssets,totalLiabilities,costOfRevenue,longTermDebt,totalDebt,interestExpense,totalLiabilitiesAndStockholdersEquity,totalAssets,accountPayables,totalNonCurrentAssets,costAndExpenses,shortTermDebt
0,2,4.023500e+10,8.284000e+09,4.670000e+08,2.530000e+08,2.970000e+08,1.658400e+10,5.171700e+10,1.234000e+10,6.830100e+10,5.610000e+09,3.675900e+10,4.120500e+10,340000000.0,6.277300e+10,6.277300e+10,1.077000e+09,5.043300e+10,6.339000e+09,4.446000e+09
1,3,3.889700e+10,1.403900e+10,3.990000e+08,2.770000e+08,4.340000e+08,1.733300e+10,5.926100e+10,1.808900e+10,7.659400e+10,6.164000e+09,4.398500e+10,4.802400e+10,371000000.0,6.864900e+10,6.864900e+10,1.624000e+09,5.056000e+10,7.031000e+09,4.039000e+09
2,1,3.804012e+09,1.141502e+09,1.279838e+09,1.141502e+09,1.141502e+09,4.437559e+09,3.766587e+09,6.395525e+09,8.204146e+09,1.404666e+09,3.281740e+09,3.281740e+09,13422000.0,1.193066e+10,1.193066e+10,3.310073e+09,5.535140e+09,2.238535e+09,0.000000e+00
3,1,5.130000e+09,1.224900e+10,8.546000e+09,1.218200e+10,1.218200e+10,2.853300e+10,1.067480e+11,2.895700e+10,1.352810e+11,4.390000e+09,7.404900e+10,8.072100e+10,596000000.0,1.488310e+11,1.488580e+11,0.000000e+00,1.199010e+11,9.646000e+09,6.672000e+09
4,2,1.013000e+09,6.132000e+08,3.886000e+08,6.132000e+08,6.132000e+08,8.932000e+08,1.328100e+09,1.591700e+09,2.221300e+09,1.202300e+09,1.259700e+09,1.853700e+09,15900000.0,2.934400e+09,2.934400e+09,2.992000e+08,1.342700e+09,1.362900e+09,5.940000e+08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
264,1,1.008259e+09,9.848300e+07,1.028490e+08,9.848300e+07,1.013630e+08,5.356280e+08,1.461275e+09,1.236947e+09,1.996903e+09,3.955110e+08,7.291650e+08,9.294470e+08,8737000.0,3.906669e+09,3.906669e+09,1.608870e+08,2.669722e+09,4.873940e+08,2.002820e+08
265,1,5.646000e+09,2.300000e+09,1.497000e+09,2.300000e+09,2.429000e+09,2.141000e+09,6.756000e+09,4.924000e+09,8.897000e+09,2.274000e+09,5.505000e+09,5.657000e+09,64000000.0,1.251400e+10,1.255100e+10,1.459000e+09,7.627000e+09,2.495000e+09,1.520000e+08
266,1,2.275530e+11,4.787900e+10,8.832000e+09,4.364000e+09,4.364000e+09,5.636300e+10,1.122570e+11,4.489300e+10,1.686200e+11,6.233200e+10,4.550200e+10,6.596000e+10,313000000.0,3.257700e+11,3.327500e+11,1.749900e+10,2.878570e+11,7.244700e+10,2.045800e+10
267,1,9.105000e+08,1.109100e+09,2.359000e+08,1.109100e+09,1.109100e+09,7.630000e+08,3.195800e+09,2.362900e+09,3.958800e+09,3.145000e+08,2.182700e+09,2.183000e+09,12300000.0,8.601900e+09,8.604200e+09,2.141000e+08,6.241300e+09,5.936000e+08,3.000000e+05
268,1,2.949980e+08,5.256930e+08,3.869080e+08,5.256930e+08,5.266030e+08,1.205300e+08,1.716350e+08,6.173930e+08,2.921650e+08,1.182500e+07,1.645370e+08,2.209430e+08,191000.0,1.073485e+09,1.073485e+09,2.568000e+06,4.560920e+08,2.010670e+08,5.640600e+07

In [395]:
postcovid_df_spearman_cor

                                       spearman
Number of Layoffs                      0.290482
netChangeInCash                        0.136517
otherAssets                            0.135753
Quarter                                0.132345
shortTermDebt                          0.130401
changeInWorkingCapital                 0.127711
industry_labelled                      0.119648
otherLiabilities                       0.107881
otherExpenses                          0.105584
otherInvestingActivites                0.104038
propertyPlantEquipmentNet              0.103145
accountsPayables                       0.094617
accountsReceivables                    0.084734
shortTermInvestments                   0.084409
totalOtherIncomeExpensesNet            0.083826
commonStockRepurchased                 0.083096
totalLiabilitiesAndStockholdersEquity  0.077697
retainedEarnings                       0.076332
capitalExpenditure                     0.072638
totalStockholdersEquity                0.071610

In [396]:
postcovid_selected_features

,Number of Layoffs,netChangeInCash,otherAssets,Quarter,shortTermDebt,changeInWorkingCapital,industry_labelled,otherLiabilities,otherExpenses,otherInvestingActivites,propertyPlantEquipmentNet,accountsPayables,accountsReceivables,shortTermInvestments,totalOtherIncomeExpensesNet,commonStockRepurchased,totalLiabilitiesAndStockholdersEquity,retainedEarnings,capitalExpenditure,totalStockholdersEquity
0,1,0.000000e+00,0.0,4,4.739000e+09,0.000000e+00,2,0.0,0.000000e+00,0.0,3.829400e+10,0.000000e+00,0.0,8.525000e+09,0.000000e+00,0.000000e+00,6.471600e+10,-8.511000e+09,0.000000e+00,-5.799000e+09
1,1,-3.648000e+09,0.0,1,9.952000e+09,-1.275000e+09,6,0.0,0.000000e+00,154000000.0,5.075000e+09,-2.580000e+08,-785000000.0,1.474000e+09,2.120000e+08,-1.470000e+09,1.431800e+11,5.103000e+09,-1.620000e+08,1.628300e+10
2,1,3.311000e+09,0.0,3,9.207000e+09,1.338000e+09,6,0.0,2.290000e+08,170000000.0,4.893000e+09,7.780000e+08,357000000.0,4.700000e+07,-2.030000e+08,-4.000000e+06,1.412920e+11,4.953000e+09,-1.770000e+08,1.599400e+10
3,1,-1.590000e+07,0.0,4,1.508000e+08,-5.440000e+07,9,0.0,1.260200e+09,1400000.0,2.635000e+08,-3.000000e+06,0.0,0.000000e+00,-7.800000e+06,0.000000e+00,3.782200e+09,8.675000e+08,-6.600000e+06,1.569200e+09
4,1,9.100000e+06,0.0,3,2.118000e+08,1.171000e+08,9,0.0,1.593400e+09,-900000.0,2.406000e+08,0.000000e+00,-50100000.0,0.000000e+00,-1.540000e+07,-2.300000e+07,4.868900e+09,1.110600e+09,-1.300000e+07,1.717200e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99,2,7.470000e+08,0.0,2,2.310000e+08,-7.300000e+07,562,0.0,5.220000e+08,-533000000.0,1.438200e+10,0.000000e+00,-88000000.0,0.000000e+00,-1.140000e+08,-2.700000e+08,3.012600e+10,1.256300e+10,-5.500000e+08,7.190000e+09
100,1,-2.952000e+09,0.0,1,1.700800e+10,-8.472000e+09,563,0.0,0.000000e+00,-421000000.0,1.271880e+11,-1.640000e+09,0.0,0.000000e+00,-2.417000e+09,-2.408000e+09,2.461420e+11,8.053200e+10,-3.539000e+09,7.689600e+10
101,2,2.108000e+09,0.0,2,1.794800e+10,4.670000e+09,563,0.0,0.000000e+00,-55000000.0,1.143920e+11,1.187000e+09,0.0,0.000000e+00,-2.100000e+08,-3.339000e+09,2.389210e+11,8.251900e+10,-3.953000e+09,7.756900e+10
102,1,6.890000e+07,0.0,1,4.196000e+08,-2.319000e+08,566,0.0,8.810000e+07,-151800000.0,1.023740e+10,5.890000e+07,-289500000.0,0.000000e+00,-1.410000e+07,-2.193000e+08,2.918270e+10,1.662500e+09,-1.810000e+08,1.157840e+10
103,1,-5.480000e+07,0.0,2,3.878000e+08,9.640000e+07,566,0.0,8.750000e+07,-207600000.0,1.005840e+10,5.570000e+07,-30900000.0,0.000000e+00,-2.870000e+07,-2.806000e+08,2.886220e+10,1.934400e+09,-2.154000e+08,1.145790e+10